version: 0.2

env:
  parameter-store:
    NPM_TOKEN: "/blackpear-cd/npm_token"
    EBX_VPCID: "/blackpear-cd/appcloud/default/VPCId"
    EBX_ELBSUBNETS: "/blackpear-cd/appcloud/default/ELBSubnets"
    EBX_SUBNETS: "/blackpear-cd/appcloud/default/Subnets"
    EBX_SSLCERT: "/blackpear-cd/appcloud/default/SSLCertificateArns"
    EBX_NOTIFICATIONTOPICARN: "/blackpear-cd/appcloud/default/NotificationTopicARN"
    EBX_TOPICARN_P1FAULT: "/blackpear-cd/appcloud/default/TopicARN/P1Fault"
    EBX_TOPICARN_P2FAULT: "/blackpear-cd/appcloud/default/TopicARN/P2Fault"
    EBX_TOPICARN_P3FAULT: "/blackpear-cd/appcloud/default/TopicARN/P3Fault"
    EBX_TOPICARN_P4FAULT: "/blackpear-cd/appcloud/default/TopicARN/P4Fault"
    EBX_TOPICARN_P5FAULT: "/blackpear-cd/appcloud/default/TopicARN/P5Fault"
    EBX_TOPICARN_WARNING: "/blackpear-cd/appcloud/default/TopicARN/Warning"
    EBX_TOPICARN_INFORMATION: "/blackpear-cd/appcloud/default/TopicARN/Information"
    EBX_TOPICARN_SECURITY: "/blackpear-cd/appcloud/default/TopicARN/Security"

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
      # Upgrade PIP to the latest version
      - pip install --upgrade pip

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      # Enable access to Black Pear organisation on NPM
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  pre_build:
    commands:
      # Install postgres if required for testing
      - |
        echo "Mongo required: ${INSTALL_TEST_MONGO}";
        if expr "${INSTALL_TEST_MONGO}" = "true" >/dev/null; then
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb;
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        fi

        echo "Postgres required: ${INSTALL_TEST_POSTGRES}";
        if expr "${INSTALL_TEST_POSTGRES}" = "true" >/dev/null; then
          apt-get update -y;
          apt-get install postgresql postgresql-contrib -y;
          service postgresql start;

          PG_CONFIG_FILE=$(ps -ef | grep postgres | sed -n '/-D /p' | sed -e 's/.*config_file=\([^ ]*\).*/\1/');

          PG_HBA_FILE=$(grep "hba_file" $PG_CONFIG_FILE | sed -e "s/.*'\([^ ]*\)'.*/\1/");

          sed -i -e 's/peer/trust/g' $PG_HBA_FILE;
          sed -i -e 's/md5/trust/g' $PG_HBA_FILE;

          service postgresql restart;

          if expr "${TEST_POSTGRES_USERNAME}" != "postgres" >/dev/null; then
            createuser -U -w postgres $TEST_POSTGRES_USERNAME;
          fi

          psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres'";
          createdb -U postgres -w -O $TEST_POSTGRES_USERNAME $TEST_POSTGRES_DB_NAME;
        fi

      # Install dependencies needed for running tests
      - npm ci

      # Discover and run unit tests
      - npm test

  build:
    commands:
      # deploy .ebextensions
      - mkdir -p .ebextensions
      - cp ./node_modules/@blackpear/cd-eb/.ebextensions/*.config .ebextensions/

      #deploy Procfile
      - cp ./node_modules/@blackpear/cd-eb/eb-Procfile Procfile

      # deploy platform hooks for dynamic NPM token fetch
      - mkdir -p .platform/hooks/prebuild .platform/confighooks/prebuild
      - cp ./node_modules/@blackpear/cd-eb/fetch-npm-token.sh .platform/hooks/prebuild/01_fetch_npm_token.sh
      - cp ./node_modules/@blackpear/cd-eb/fetch-npm-token.sh .platform/confighooks/prebuild/01_fetch_npm_token.sh
      - chmod +x .platform/hooks/prebuild/01_fetch_npm_token.sh .platform/confighooks/prebuild/01_fetch_npm_token.sh

      # create local.config
      - echo "option_settings:" > .ebextensions/local.config
      - echo "  aws:ec2:vpc:" >> .ebextensions/local.config
      - echo -n "    VPCId:" >> .ebextensions/local.config
      - echo " $EBX_VPCID" >> .ebextensions/local.config
      - echo -n "    ELBSubnets:" >> .ebextensions/local.config
      - echo " $EBX_ELBSUBNETS" >> .ebextensions/local.config
      - echo -n "    Subnets:" >> .ebextensions/local.config
      - echo " $EBX_SUBNETS" >> .ebextensions/local.config
      - echo "  aws:elbv2:listener:443:" >> .ebextensions/local.config
      - echo -n "    SSLCertificateArns:" >> .ebextensions/local.config
      - echo " $EBX_SSLCERT" >> .ebextensions/local.config
      - echo "  aws:elasticbeanstalk:sns:topics:" >> .ebextensions/local.config
      - echo -n "    Notification Topic ARN:" >> .ebextensions/local.config
      - echo " $EBX_NOTIFICATIONTOPICARN" >> .ebextensions/local.config

      # SNS notification topic ARNs in local.config
      - echo "  aws:elasticbeanstalk:customoption:" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_P1FAULT:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_P1FAULT" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_P2FAULT:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_P2FAULT" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_P3FAULT:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_P3FAULT" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_P4FAULT:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_P4FAULT" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_P5FAULT:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_P5FAULT" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_WARNING:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_WARNING" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_INFORMATION:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_INFORMATION" >> .ebextensions/local.config
      - echo -n "    EBX_TOPICARN_SECURITY:" >> .ebextensions/local.config
      - echo " $EBX_TOPICARN_SECURITY" >> .ebextensions/local.config

      # remove node_modules
      - rm -r node_modules

artifacts:
  files:
    - '**/*'
